USE gestioncomercialintegral;

DROP TABLE IF EXISTS LOG_AUDITORIA_CLIENTE;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_CLIENTE
(
ID_LOG INT AUTO_INCREMENT ,
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
USUARIO VARCHAR(100) , 
FECHA_UPD_INS_DEL DATE , 
PRIMARY KEY (ID_LOG)
)
;
DROP TABLE IF EXISTS LOG_AUDITORIA_CLIENTE2;
CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_CLIENTE2
(
ID_LOG INT AUTO_INCREMENT ,
CAMPONUEVO_CAMPOANTERIOR VARCHAR(300), 
NOMBRE_DE_ACCION VARCHAR(10) ,
NOMBRE_TABLA VARCHAR(50) ,
USUARIO VARCHAR(100) ,
FECHA_UPD_INS_DEL DATE    ,
PRIMARY KEY (ID_LOG)
)
;
DELIMITER //
CREATE TRIGGER TRG_LOG_AUDITORIA_CLIENTE AFTER INSERT ON gestioncomercialintegral.cliente
FOR EACH ROW 
BEGIN

INSERT INTO LOG_AUDITORIA_CLIENTE (NOMBRE_DE_ACCION , NOMBRE_TABLA , USUARIO,FECHA_UPD_INS_DEL)
VALUES ( 'INSERT' , 'cliente' ,CURRENT_USER() , NOW());

END//
DELIMITER ;

DELIMITER //
CREATE TRIGGER  TRG_LOG_AUDITORIA_CLIENTE2 AFTER INSERT ON gestioncomercialintegral.cliente
FOR EACH ROW 
BEGIN
 
INSERT INTO  LOG_AUDITORIA_CLIENTE2 (CAMPONUEVO_CAMPOANTERIOR, NOMBRE_DE_ACCION , NOMBRE_TABLA ,USUARIO, FECHA_UPD_INS_DEL)
VALUES ( CONCAT(NEW.id_cliente,' , ', NEW.nombre,' , ', NEW.mail,' , ', NEW.direccion,' , ', NEW.region), 
          'INSERT' , 'cliente' ,CURRENT_USER(), NOW()); 
 
END//
DELIMITER ;

INSERT INTO cliente (id_cliente,nombre,mail,direccion,region) VALUES (16,'Caro SA','caro@gmail.com','PAZ 647','NORTE');

SELECT * FROM cliente;
SELECT * FROM LOG_AUDITORIA_CLIENTE;
SELECT * FROM LOG_AUDITORIA_CLIENTE2;


